damienmaguire/Stm32-vcu

- include/i3LIM.h
- src/i3LIM.cpp
- src/stm32_vcu.cpp
This series of commits converts values within the i3LIM module which have a fixed set of values to use enumerated types rather than a raw value with #defined constants. This gives the compiler more opportunities to stop errors and, I think, makes the code clearer and easier to maintain.
> Update i3LIM charger to use enums rather than raw values

- src/i3LIM.cpp
During the ChargePhase::Subpoena (pre-charge) we wait
for the contactor voltage to get within an acceptable range.
Once this happens the contactors are requested to close.
We should give time for the contactors to close before
moving to the ChargePhase::EnergyTransfer.
There is a possibility during lim_state 4 that the contactor
voltage drifts outside the acceptable range before we close
the contactors. If this happens reset the timer until it comes
back inside the range.
> i3LIM: Give contactors time to close before starting energy transfer

- include/param_prj.h
- src/i3LIM.cpp
Report the CCS contactor state as a read-only parameter.
Use the change in CCS contactor state to advance out of
Subpoena/pre-charge and into the EnergyTransfer phase
rather than wait for a fixed period of time.
This fixes a bug where the code would get stuck in lim_state
== 5 because lim_stateCnt was not being incremented so
the timer waiting for contactors to close never completed.
Tests:
- Compile tested only
> i3LIM:Proceed to Energy Transfer when contactors report closed

- include/Can_VAG.h
- src/Can_VAG.cpp
- src/stm32_vcu.cpp
Content of 0x288 doesn't seem to matter for the traction/ESP control light just requires the ID to be present.
> Adding RPM for VAG and 0x288 which turns off the traction control light

- include/param_prj.h
- include/throttle.h
- src/stm32_vcu.cpp
- src/throttle.cpp
- src/utils.cpp
Bumped version number, added throtdead parameter for a deadzone of the throttle input. This avoids torque creeping at idle.
Some cleaning of the indentation and changed the copyright notice in the parameter file (this is just the beginning.)
> Added Deadzone for the throttle

- src/utils.cpp
No matter what the previous functions are doing, it should never lead to a torque request outside of the range [-100.0, 100.0]. This could lead to wrap arounds or "funny" behavior with the inverters.
> Added a final range check for finalSpnt

- include/anain_prj.h
- include/digio_prj.h
- include/hwdefs.h
- include/leafinv.h
- include/outlanderinverter.h
- include/param_prj.h
- include/throttle.h
- src/leafinv.cpp
- src/outlanderinverter.cpp
- src/stm32_vcu.cpp
- src/throttle.cpp
Fix: Added 10ms inverter task call to the main 10ms task, fixing the Leaf inverter. Removed doubled defines from stm32_vcu.cpp (present in param_prj.h). Removed double check if-else for VAG. Updated some comments and copyright notices and cleaned up some indentations. (No changes to the binary resulting from all changes except the aforementioned fix)
> Fix: Leaf inverter not going into run mode

- include/leafinv.h
- include/param_prj.h
- src/leafinv.cpp
- src/stm32_vcu.cpp
Increased Version number to 1.09.D
Changed the stm32_vcu.cpp such that the Leaf tasks are called in RUN mode as well when the Leaf PDM is configured as charger to keep the DC/DC converter running but avoiding a double call if the Leaf inverter AND PDM are used.
> Leaf DC/DC fixes and cleanup

- src/stm32_vcu.cpp
Without this patch, a Zombieverter with both a Leaf inverter and a Leaf PDM will not operate in charge mode.
> Send all messages to leaf v2 PDM when in charge mode

- include/param_prj.h
Found while testing an update to libopeninv
which prevents duplicate parameter unique
ids. Fixing this will allow correct reading of
these values of CAN SDO with an updated
libopeninv. As these are value parameters it
doesn't affect saved parameters or the web
interface.
Tests:
- Compile tested with https://github.com/davefiddes/libopeninv/tree/guaranteed-unique-param-ids
> Fix a parameter id clash between ChgT and CCS_Ireq

- Makefile
- include/bms.h
- include/daisychainbms.h
- include/param_prj.h
- include/simpbms.h
- include/stm32_vcu.h
- src/daisychainbms.cpp
- src/simpbms.cpp
- src/stm32_vcu.cpp
This pull request is a work in progress. It aims to add modular BMS support to Zombieverter.
Current goals are as follows:
* Fully modular architecture with selectable BMS hardware
* Receive cell voltage data from BMS
* Receive cell temperature data from BMS
* Inhibit charging if indicated by configurable voltage and temperature limits
* Inhibit charging if indicated by BMS
* Limit charge rate if indicated by BMS
Possible future goals:
* Limit discharge rate if indicated by BMS
* State of charge calculation using fused shunt and BMS data
> Modular BMS

- include/param_prj.h
- src/stm32_vcu.cpp
Make it possible to control where the CanMap messages are being sent.  Feel free to pick a better name.  This will also require a reset if you ever change it.
> Make the CanMap device configurable.

- include/anain_prj.h
- include/iomatrix.h
- include/param_prj.h
- src/iomatrix.cpp
- src/stm32_vcu.cpp
Using mappable analogue in pin with a vacuum sensor to turn on an electric brake boost pump until the sensor returns brkVacThresh. When it falls below the BrkVacHyst value, the pump is turned back on.
> Adding Support for a Vacuum Sensor and Brake Boost Pump

- Makefile
- include/BMW_E31.h
- include/BMW_E65.h
- include/CPC.h
- include/ElconCharger.h
- include/NoInverter.h
- include/heater.h
- include/hwinit.h
- include/no_Lever.h
- include/param_prj.h
- include/rearoutlanderinverter.h
- include/stm32_vcu.h
- include/throttle.h
- src/BMW_E31.cpp
- src/BMW_E65.cpp
- src/CPC.cpp
- src/Can_OI.cpp
- src/ElconCharger.cpp
- src/GS450H.cpp
- src/RearOutlanderinverter.cpp
- src/hwinit.cpp
- src/i3LIM.cpp
- src/stm32_vcu.cpp
- src/throttle.cpp
- src/utils.cpp
- stm32-vcu.cbp
This adds:
1. Rear outlander inverter control as per: https://github.com/damienmaguire/Stm32-vcu/pull/75 
2. Regen - Tested on BenB Mgf with Outlander Rear inverter.
3. Ability to have no inverter selected
4. Improved E90 support, allowing BMW CAN to sleep - Jamie Jones validated on his BMW
5. EVS-CPC support as a charing interface - Validated functionality on Mr600v datsun
6. Elcon charge CAN control - Validated functionality on Mr600v datsun
> Regen+rear outlander

- include/GS450H.h
- include/leafinv.h
- include/param_prj.h
- include/throttle.h
- src/CANSPI.cpp
- src/GS450H.cpp
- src/RearOutlanderinverter.cpp
- src/leafinv.cpp
- src/stm32_vcu.cpp
- src/throttle.cpp
- src/utils.cpp
- stm32-vcu.cbp
Param:Speed has now been cleaned up in all files, making sure only the use ABS when required.
Created Param to inverter motor rotation - only really applicable to Outlander, but also implemented on Leaf.
Implemented, if pedal is steady no regen allowed but still taper the PotNom on speed base.
Clean up work in GS450h
-Checksum
-Create template for Prius, IS300h and GS450h specifics within functions
clean up work in Leaf
-Propper 15bit decoding of speed
-Added reversemotor
RearOutlander
-Added reversemotor
Param
-Added reversemotor param
Created Param to inverter motor rotation - only really applicable to Outlander, but also implemented on Leaf.
-Added regenendrpm
rpm under which regen is forced to 0, to remove jerkyness
-can3speed
added 100kbps
> Regen improvements v2

- include/param_prj.h
- src/throttle.cpp
- src/utils.cpp
Regen ramping up and down fixed. Was not working in the ramp in
Potnom is now forced into a decimal value with one place.0.1
Was limited due to the function change (map) being interger based instead of float.
> Fix Regen ramping + 0.1 Dec Potnom created

- include/param_prj.h
- src/RearOutlanderinverter.cpp
- src/stm32_vcu.cpp
- src/throttle.cpp
Clean up the serttings of reversemotor param, force zero for all except outlander rear.
Correction for unsigned torque request number when using negatives.
> Reverse Motor Fix Outland Rear

- include/param_prj.h
There are punctuation errors in the units for the
"Inverter", "chargemodes", "CAN3Speed" and
"OutXFunc". The first 3 cause parse errors for the openinverter can tool when trying to read the
parameter database from the device as covered in
https://github.com/davefiddes/openinverter-can-tool/issues/4. Whilst this can be worked around client side it is better fixed in the Zombieverter.
The issue likely causes problems with the web interface missing one or more items from the drop down.
Tests:
- Compile tested only
- Verify a fixed database is parsed correctly by OIC
> Fix punctuation of enum parameters

- .github/workflows/CI-build.yml
- .vscode/launch.json
- Makefile
- README.md
- include/stm32_vcu.h
- include/utils.h
- src/BMW_E31.cpp
- src/BMW_E39.cpp
- src/BMW_E65.cpp
- src/utils.cpp
- test/Makefile
- test/test_throttle.cpp
Enable continuous integration builds like the stm32-sine and ccs32clara projects to catch build errors before PRs are raised.
Fix a bunch of problems with the current build and return the unit tests to operation.
> Build improvements

- include/utils.h
- src/utils.cpp
Reinstate the move of utils::change() to be an inline function similar to commit 467955d7. This allows
utils.h to be used in both the Linux and STM32 builds. Currently utils.cpp is highly platform specific and cannot be built for Linux x86.
Tests:
- Build for STM32 and x86 Linux
- Run unit tests on Linux successfully
> Fix unit test build

- src/stm32_vcu.cpp
Fix for issue reported by BenB SomersetEV
> Check for reversemotor and multiply by direction

- include/outlanderCharger.h
- include/param_prj.h
- src/GS450H.cpp
- src/outlanderCharger.cpp
- src/stm32_vcu.cpp
- src/utils.cpp
Shutdown Delay + Jamie Merge
-Reuse delay from contactor switching to add delay between shutting down INV Out and opening contactors.
-Outlander Charger UDC measurement option
-Fix GS450h Oil Pump PWM inverted
-Added Gear option High forward Low reverse
> Update shutdown delay

- src/stm32_vcu.cpp
Regen Brake Light Fix - Use potnom for comparison to simplify and fix
> Regen Brake Light Fix

- Makefile
Commit 48d6693e pulled in an updated libopencm3
for undocumented reasons. In principle this is a good idea as it fixes a nasty stack initialization bug fixed by @uhi22 as discussed in
https://github.com/uhi22/ccs32clara/issues/17.
Unfortunately the fix breaks the libopencm3 build for all platforms except STM32F1.
The fix is to limit the build of libopencm3 to just the STM32F1 platform in the same way as the CCS32clara firmware.
Tests:
- Carry out a full clean build locally
- Check GitHub CI build after push before raising a PR
> Fix clean build due to change in libopencm3

- src/stm32_vcu.cpp
Changes to make sure to only update rlyDly when leaving a state.
rlydly is increased to u_int16
rlydly is increased to 250 when going into off
> fix shutdown logic

- include/leafinv.h
- src/NissanPDM.cpp
Leaf Inv UDCinv fix, remove /2 from .h
Leaf PDM fix, only use 0x390 for determining to start charge Add info on available AC current from power
Setup to allow potential using of Spoofed CP and PP with other charge interfaces.
> Leaf Updates 241113

- include/digio_prj.h
- include/iomatrix.h
- include/param_prj.h
- src/GS450H.cpp
- src/iomatrix.cpp
- src/stm32_vcu.cpp
HeatReq - if no input selected it no longer forces a state
Input PB1 PB2 and PB3 are also now mappable. Added Inverter logic options for the pin types.
!!!requires the latest libopeninv
> HeatReq Fix + PB123 Mapable

- src/NissanPDM.cpp
- src/leafinv.cpp
This PR aims to save some memory (6 bytes!) and simplify the code. We also lower CPU usage by sending the 50B message at 100ms instead of 10ms.
We use correct Nissan terminology (MPRUN for the counters), and use the same variable for all 10ms messages.
> LEAF PDM/Inverter: Unify MPRUN handling to save memory

- README.md
Add command for how to easily install gcc-arm-none-eabi on Linux
> Documentation: Update compiling section

- include/param_prj.h
The TorqDerate spot value does not display properly in the esp8266-web-interface. With a TorqDerate of 13 it displays UDClimHigh. The problem is due to "+" being an invalid character for enum value names. As the field is used as a bitfield change the definition to a bitfield enum which the web interface can display. Verify behaviour with power-of-two values and mix of values between 0 and 31.
Refix punctuation of CAN3Speed enum to allow it to be parsed by openinverter-can-tool
Tests:
- Verify reading of TorqDerate and read/write of CAN3Speed parameters with:
- esp8266-web-interface (tip) on Wemos D1 Mini clone
- openinverter-can-tool 0.2.1
> Fix TorqDerate and CAN3Speed enum definitions

- include/leafbms.h
- include/leafinv.h
- src/leafbms.cpp
- src/leafinv.cpp
This PR adds CRC checking on all incoming LEAF BMS messages that have a CRC
EV conversions and high voltage systems are noisy. Incase a high voltage connection comes too close to an unshielded CAN network, message data can become corrupt. Incase the VCU interprets one of these corrupt frames, it can wreck havoc on the decision making (Imagine suddenly seeing undervoltage and the vehicle cuts out at a critical moment!). This is why OEMs use CRCs, counters and other methods to ensure CAN data is valid.
We now use the already existing CRC algorithm used to sign outgoing messages, in reverse. Incoming messages get their CRC byte inspected, incase we notice that the actual value deviates from the calculated CRC, we simply discard the message.
> [!WARNING]  
> Code has not been tested on a …
> Nissan LEAF: Increase robustness by using CRC bit on incoming messages

- include/param_prj.h
- src/GS450H.cpp
- src/NissanPDM.cpp
IS300h had issues of inverter comms being dead. Now resolved  by removing MG1 and MG2 speed reset. Needs further investigation in the future on how to resolve comms loss.
-Tested on Andybp Z4 with IS300h
ADDED uprevision in release prep.
> IS300h FIX

- src/stm32_vcu.cpp
There's a possible bug here. The code deals with `ppValue < ppThresh` and `ppValue > ppThresh` but not `ppValue == ppThresh`. It's probably not likely that this would occur often, but it could lead weird behavior when ppValue is near ppThresh. Noise could possibly produce irratic results. E.g., plug in first time, charge fails, plug in second time, charge succeeds.
I've set the `==` condition on the positive side because I think that is what the user expectation would be.
Another option would be to set the `==` on the negative side.
Yet another option would be to remove the `if (ppValue > ppThresh)` condition from the else block.
> Deal with ppValue == ppThresh scenario

- src/hwinit.cpp
Fix for PwmTim3 as no PWM output. Caused by CPspoofPres being undefined.
> Fix PwmTim3 no outputting PWM

- src/stm32_vcu.cpp
Reverts damienmaguire/Stm32-vcu#151
Needs more testing.
> Revert "Update stm32_vcu.cpp"

- include/param_prj.h
- src/NissanPDM.cpp
- src/outlanderCharger.cpp
- src/stm32_vcu.cpp
Interface Chademo - Does not force charge on Nissan PDM, requires PDM to report Plug Present
Outlander Charger
- No Charge Interface, utilize PP detect to try going into charge mode -will enter Charge Mode for 30s: HV ON, Inv Relay ON -If Charger does not report CP duty above stay in Charge Mode
-Chademo implementation -NOT WORKING with Outlander Charger
Nissan Leaf PDM
-Add Plug present for byte 5 being 0xn4
STM32_VCU
-Move running of 200ms tasks to front of 200ms main -Add comments about charging and logic sections
-Set PlugDet with PP detect logic
-Add HVrequest logic to enable HV
13-02-2025 15:37 UK - Tested on bench by Tom
> Outlander update + Charger Interface Clean + HVrequest

- src/utils.cpp
Reverts damienmaguire/Stm32-vcu#164
Causes issues if UDC2 not wired.
> Revert "ISA Shunt UDCsw"

- include/param_prj.h
- src/throttle.cpp
- src/utils.cpp
IMPROVEMENT
Issue:
Small blip and instability noticed, not always log-able, when apply low throttle levels. Issue traced to IDC and UDC limiters.
Fix:
Simplification of limiters  and moving the throttle ramp to last step in PotNom calculation
Additional Change:
Cruise code potential impact on throttle removed fully disabled. Never reachable except via SDO mapping.
> Reordering of Throttle ramping eliminating ramping of limits

- include/param_prj.h
- src/chademo.cpp
- src/stm32_vcu.cpp
- src/utils.cpp
Chademo and PP compatibility Update
-PP detect is bypassed if DCFCrequest input is active
-Chademo clean up on reading input to stop always high if un specified
-din_cruise reused for HVreq input
> Chademo and pp compatibility update
