damienmaguire/Stm32-vcu

- src/Can_E46.cpp
More thoroughly document bytes for E46.
> Potentially fix tach comparison error.

- src/stm32_vcu.cpp
Modify various logic constructs.
Clean up compiler warnings.
Rework selection of Vehicle CAN messages.
Modify whitespace.
> First cleanup of src/stm32_vcu.cpp

- .gitignore
- src/stm32_vcu.cpp
I think this is what you were trying to do?
> Add linker map to .gitignore. Add 200ms task.

- include/chademo.h
- src/chademo.cpp
I see it is not used yet but I added some sanity checking to the CHAdeMO module
> Updated CHAdeMO module with current and voltage checks.

- src/hwinit.cpp
- src/stm32_vcu.cpp
As is INV_POWER and OIL_PWM are trying to share PA8.
> Fix oil_pwm setup. Needs remapping to PE9

- include/param_prj.h
- src/CANSPI.cpp
- src/GS450H.cpp
- src/isa_shunt.cpp
- src/stm32_vcu.cpp
Please only merge this if parameter copies in spot values are indeed redundant
> Removed copies of parameters in spot values

- include/iomatrix.h
- include/param_prj.h
- src/chademo.cpp
- src/extCharger.cpp
- src/iomatrix.cpp
- src/stm32_vcu.cpp
We may want to separate the outputs from the inputs to do some sanity checking, but this seems ok for now.
> Add 12v_gpin and hv_req to IOMatrix.

- Makefile
Make sure the right files are recompiled when editing headers.
> Add dependencies to Makefile

- include/param_prj.h
Missed these updates the first time.
> Fix missed params updates for iomatrix_inputs change

- src/i3LIM.cpp
Type 1 CCS i3lim fix - tested by Shockazulu1 on Open Inverter
> Fix for type 1 CCS with I3Lim - TomDB

- src/outlanderCharger.cpp
Can now run with no charge interface selected. Also disables 285 canbus message when not charging as that can interfere with Outlander Inverter.
> Outlander Charger updates

- src/GS450H.cpp
- src/stm32_vcu.cpp
Tested on my car and Andy's Z3
> Fixing issue where the vacuum pump would remain on if car turned off during pumping

- include/GS450H.h
- include/param_prj.h
- include/throttle.h
- src/GS450H.cpp
- src/stm32_vcu.cpp
- src/throttle.cpp
- src/utils.cpp
-Autoshifting for GS450h implementation base: Set gear to Auto for testing.
-Steady Pedal Operation:
regen limit/ pedal 0 is set based on speed until you release the accelerator. This way a "steady" pedal is a "steady" potnom regardless of speed. Unless you release the pedal, regen is always speed dependant
> DEV ONLY: Steady pedal regen update + shifting gs450h

- src/GS450H.cpp
To improve auto shift reduce regen in low gear by half.
> Reduced regen in Low Gear

- src/BMW_E39.cpp
- src/GS450H.cpp
- src/throttle.cpp
Remove "Steady Pedal" Behaviour, not deemed effective
GS450h Auto Shift Ramp back in now same as Param Throtramp
BMW E39 also has CANwake via receiving 0x153 from ABS
> Steady pedal Removal + shifting gs450h ramp + BMW E39 0x153 CAN wake

- src/GS450H.cpp
5x throtramp torque pull down to 0 before shifting
> UPDATE for TESTING: Shift point torque ramp down

- src/throttle.cpp
Remove unwanted behaviour generated by the RegenendRpm parameter
> Throttle RegenendRpm fix

- Makefile
- include/Focci.h
- include/iomatrix.h
- include/param_prj.h
- include/stm32_vcu.h
- include/utils.h
- src/Focci.cpp
- src/hwinit.cpp
- src/i3LIM.cpp
- src/outlanderCharger.cpp
- src/stm32_vcu.cpp
- src/utils.cpp
- stm32-vcu.cbp
Focci Support:
-Functionality like BMW I3 LIM for AC and DC charging. 
-Automatic SDO configuration of Focci CAN messages
CPspoofing
-PWM3 can now output 12V PWM inline with reported EVSE Current limit -Outlander Charger CP spoofing code removed
Note some large modified files are due to stupid formatting changes.
> First Commit Focci Implementation

- Makefile
- include/BMW_E65.h
- include/OutlanderCanHeater.h
- include/OutlanderHeartBeat.h
- include/chargerint.h
- include/heater.h
- include/kangoobms.h
- include/param_prj.h
- include/stm32_vcu.h
- include/utils.h
- src/BMW_E65.cpp
- src/OutlanderCanHeater.cpp
- src/OutlanderHeartBeat.cpp
- src/RearOutlanderinverter.cpp
- src/V_Classic.cpp
- src/kangoobms.cpp
- src/leafbms.cpp
- src/outlanderCharger.cpp
- src/stm32_vcu.cpp
- src/utils.cpp
- stm32-vcu.cbp
-E65 updates
-Vehicle speed
-Warning Lights
-Digipots for FuelLevel
-Outlander CAN Heater
-Heater CAN Param added
-Outlander CAN heartbeat message implemented (shared between components)
-Kangoo 33kWh BMS added
> Feature update sept24 - Jamie Jones Special Edition

- include/param_prj.h
- src/GS450H.cpp
Stop IS300h reinit upon incorrect checksum - commented out //inv_status=0;
MG1 Blending option in param MotorsAct, option 3 - MG1 only ramps in above 50% Potnom
> Is300h+gs450h changes

- src/OutlanderCanHeater.cpp
Current code fails to look at the current temperature
> Fixing outlander heater bug

- src/GS450H.cpp
Fix GS450h temps they should be an Interger as below zero values jump to 255,254
> Fix GS450h temps

- src/kangoobms.cpp
Fixing bug where the most significant bit of the 9 bit data for the kwh remaining data was ignored.
> Fixing remaining kWh data

- include/param_prj.h
Outlander rear motor works really well with -35% max regen.
> increase max regen limits

- src/Focci.cpp
Implement CCS charging with Foccci.
Implement last section of logic to allow DC fast charging via Foccci.
Proven by Jamie in his BMW E92.
> Foccci ccs

- include/simpbms.h
- src/simpbms.cpp
Fix for https://github.com/damienmaguire/Stm32-vcu/issues/77
> Fix SimpBMS MaxChargingCurrent scaling

- src/utils.cpp
ISA Shunt
-Add Auto UdcSW update based on UDC2
-Remove inspection of UDC2 and UDC3 vs UDC  no longer relevant for a long time now.
> ISA Shunt UDCsw

- Makefile
- include/ElconDCDC.h
- include/param_prj.h
- src/ElconDCDC.cpp
- src/stm32_vcu.cpp
Added messages required by some Elcon Charger/DCDC units
> Elcon DCDC

- CONTRIBUTING.md
This PR adds a note on how the project code formatting works. 
It can be helpful for new contributions, or when something goes wrong with the bot that should automatically format
CONTRIBUTING.md gets a new section
> Contributing: Add note on Code Formatting
